export const STORAGE_KEYS = {
  auth: 'myapp_auth',
};

export const BOOKING_TABS = ['upcoming', 'completed', 'cancelled'];

export const STATUS_BY_TAB = {
  upcoming: ['pending', 'accepted', 'in_progress'],
  completed: ['completed'],
  cancelled: ['cancelled', 'rejected'],
};

export const STATUS_LABELS = {
  pending: 'Pending',
  accepted: 'Accepted',
  in_progress: 'In Progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  rejected: 'Rejected',
};

export const SERVICES_CATALOG = [
  {
    id: 'svc-1',
    title: 'Painting House Walls',
    category: 'Painting',
    provider: 'Brooklyn Simmons',
    price: 3,
    rating: 4.8,
    district: 'Colombo',
    popularity: 95,
    image: 'https://images.unsplash.com/photo-1581579188869-4f24f15ddf4c?auto=format&fit=crop&w=900&q=80',
    options: ['Size of house', 'Paint finish', 'Color count'],
  },
  {
    id: 'svc-2',
    title: 'Laundry Services',
    category: 'Laundry',
    provider: 'Jenny Cooper',
    price: 3,
    rating: 4.5,
    district: 'Gampaha',
    popularity: 76,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    options: ['Weight class', 'Ironing service', 'Fragrance'],
  },
  {
    id: 'svc-3',
    title: 'Appliance Services',
    category: 'Appliance',
    provider: 'Cameron Williamson',
    price: 4,
    rating: 4.2,
    district: 'Kandy',
    popularity: 61,
    image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=900&q=80',
    options: ['Working machine', 'Issue type', 'Urgency'],
  },
  {
    id: 'svc-4',
    title: 'Plumbing Repairing',
    category: 'Plumbing',
    provider: 'Theresa Webb',
    price: 4,
    rating: 4.9,
    district: 'Colombo',
    popularity: 97,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80',
    options: ['Water points', 'Damage observed', 'Need spare parts'],
  },
  {
    id: 'svc-5',
    title: 'House Shifting',
    category: 'Shifting',
    provider: 'Courtney Henry',
    price: 5,
    rating: 4.4,
    district: 'Matara',
    popularity: 58,
    image: 'https://images.unsplash.com/photo-1628191018452-54f384f5f6fd?auto=format&fit=crop&w=900&q=80',
    options: ['Origin', 'Destination', 'Large items'],
  },
];

export const SERVICE_PROVIDERS = {
  'svc-1': [
    {
      id: 'usr-paint-1',
      name: 'Kasun Perera',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      headline: 'Wall finishing specialist',
      providerType: 'Individual',
      district: 'Colombo',
      phone: '+94771234567',
      rating: 4.8,
      reviewCount: 142,
      completedJobs: 320,
      responseTime: '10 mins',
      price: 3,
      services: ['Interior painting', 'Exterior painting', 'Texture finish'],
      workMention: 'Careful masking and clean edging for every room.',
      reviews: [
        { by: 'Nadeesha', text: 'Very clean finish and on time.', rating: 5 },
        { by: 'Ruwan', text: 'Polite and professional painter.', rating: 4.5 },
      ],
    },
    {
      id: 'usr-paint-2',
      name: 'ColorFix Team',
      photo: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=400&q=80',
      headline: 'Fast team for full-house paint jobs',
      providerType: 'Team',
      district: 'Gampaha',
      phone: '+94779876543',
      rating: 4.6,
      reviewCount: 96,
      completedJobs: 210,
      responseTime: '18 mins',
      price: 4,
      services: ['Color consultation', 'Primer coating', 'Door and frame paint'],
      workMention: 'Quick turnaround with daily progress updates.',
      reviews: [
        { by: 'Ishara', text: 'Team worked fast and neat.', rating: 4.5 },
        { by: 'Piumi', text: 'Good result for the price.', rating: 4.5 },
      ],
    },
    {
      id: 'usr-paint-3',
      name: 'Prime Coat Agency',
      photo: 'https://images.unsplash.com/photo-1546961329-78bef0414d7c?auto=format&fit=crop&w=400&q=80',
      headline: 'Premium paint and finish agency',
      providerType: 'Agency',
      district: 'Kandy',
      phone: '+94774561234',
      rating: 4.9,
      reviewCount: 188,
      completedJobs: 470,
      responseTime: '8 mins',
      price: 5,
      services: ['Luxury wall coats', 'Moisture-resistant paint', 'Post-work cleanup'],
      workMention: 'High-end finish with strict quality checks.',
      reviews: [
        { by: 'Thilini', text: 'Premium quality work.', rating: 5 },
        { by: 'Sahan', text: 'Worth every rupee.', rating: 5 },
      ],
    },
  ],
  'svc-2': [
    {
      id: 'usr-laundry-1',
      name: 'FreshFold Laundry',
      photo: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=400&q=80',
      headline: 'Pickup and delivery laundry service',
      providerType: 'Team',
      district: 'Colombo',
      phone: '+94772111000',
      rating: 4.7,
      reviewCount: 132,
      completedJobs: 510,
      responseTime: '12 mins',
      price: 3,
      services: ['Wash and fold', 'Steam ironing', 'Express delivery'],
      workMention: 'Gentle wash cycles with same-day delivery options.',
      reviews: [
        { by: 'Dilan', text: 'Clothes came back fresh and folded.', rating: 5 },
        { by: 'Umesha', text: 'On-time pickup and delivery.', rating: 4.5 },
      ],
    },
    {
      id: 'usr-laundry-2',
      name: 'Nimali Fernando',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
      headline: 'Home-based careful fabric care',
      providerType: 'Individual',
      district: 'Gampaha',
      phone: '+94775444000',
      rating: 4.4,
      reviewCount: 58,
      completedJobs: 170,
      responseTime: '20 mins',
      price: 3,
      services: ['Daily wear cleaning', 'Delicate fabric wash', 'Packing by category'],
      workMention: 'Extra care for delicate and baby clothes.',
      reviews: [
        { by: 'Tharindu', text: 'Budget friendly and reliable.', rating: 4.5 },
      ],
    },
  ],
  'svc-3': [
    {
      id: 'usr-app-1',
      name: 'TechCare Services',
      photo: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=400&q=80',
      headline: 'Certified appliance technicians',
      providerType: 'Agency',
      district: 'Colombo',
      phone: '+94770011223',
      rating: 4.8,
      reviewCount: 201,
      completedJobs: 390,
      responseTime: '9 mins',
      price: 4,
      services: ['Washing machine repair', 'Fridge diagnostics', 'Microwave servicing'],
      workMention: 'Troubleshooting-first approach before part replacement.',
      reviews: [
        { by: 'Niroshan', text: 'Fixed my washing machine quickly.', rating: 5 },
      ],
    },
    {
      id: 'usr-app-2',
      name: 'Raveen Electronics',
      photo: 'https://images.unsplash.com/photo-1557862921-37829c790f19?auto=format&fit=crop&w=400&q=80',
      headline: 'Affordable home appliance repairs',
      providerType: 'Individual',
      district: 'Kandy',
      phone: '+94776677889',
      rating: 4.5,
      reviewCount: 80,
      completedJobs: 190,
      responseTime: '16 mins',
      price: 4,
      services: ['Small appliance fixes', 'Motor replacement', 'Routine checks'],
      workMention: 'Clear explanation of issue and spare-part costs.',
      reviews: [
        { by: 'Nisala', text: 'Good diagnosis and fair price.', rating: 4.5 },
      ],
    },
  ],
  'svc-4': [
    {
      id: 'usr-plumb-1',
      name: 'AquaFix Plumbing',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      headline: 'Emergency leak and pipe repair team',
      providerType: 'Team',
      district: 'Colombo',
      phone: '+94772223344',
      rating: 4.9,
      reviewCount: 276,
      completedJobs: 620,
      responseTime: '7 mins',
      price: 5,
      services: ['Leak repair', 'Tap replacement', 'Pipe rerouting'],
      workMention: 'Fast emergency response with durable plumbing fixes.',
      reviews: [
        { by: 'Shamila', text: 'Leak fixed within one hour.', rating: 5 },
      ],
    },
    {
      id: 'usr-plumb-2',
      name: 'Theresa Webb',
      photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
      headline: 'Experienced household plumbing expert',
      providerType: 'Individual',
      district: 'Colombo',
      phone: '+94773335566',
      rating: 4.7,
      reviewCount: 145,
      completedJobs: 350,
      responseTime: '14 mins',
      price: 4,
      services: ['Kitchen sink repair', 'Bathroom fitting', 'Water pressure checks'],
      workMention: 'Neat pipe work and detailed post-service checks.',
      reviews: [
        { by: 'Chamari', text: 'Very helpful and careful work.', rating: 4.5 },
      ],
    },
  ],
  'svc-5': [
    {
      id: 'usr-shift-1',
      name: 'MoveRight Team',
      photo: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80',
      headline: 'Safe home and office movers',
      providerType: 'Team',
      district: 'Matara',
      phone: '+94778889900',
      rating: 4.5,
      reviewCount: 109,
      completedJobs: 240,
      responseTime: '22 mins',
      price: 5,
      services: ['Furniture moving', 'Packing support', 'Loading and unloading'],
      workMention: 'Secure packing and careful transport handling.',
      reviews: [
        { by: 'Amesh', text: 'Safe handling of furniture.', rating: 4.5 },
      ],
    },
    {
      id: 'usr-shift-2',
      name: 'Rapid Movers Lanka',
      photo: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=400&q=80',
      headline: 'Full-service relocation agency',
      providerType: 'Agency',
      district: 'Galle',
      phone: '+94775556677',
      rating: 4.8,
      reviewCount: 168,
      completedJobs: 410,
      responseTime: '11 mins',
      price: 5,
      services: ['Whole-home shifting', 'Fragile item care', 'Multi-stop moves'],
      workMention: 'Well-coordinated teams for long-distance moving.',
      reviews: [
        { by: 'Anuki', text: 'Well organized moving crew.', rating: 5 },
      ],
    },
  ],
};

export const DEFAULT_BOOKINGS = [
  {
    _id: 'bk-1',
    serviceTitle: 'Plumbing Repair',
    providerName: 'Theresa Webb',
    status: 'pending',
    scheduledAt: new Date(Date.now() + 3600 * 1000 * 24).toISOString(),
    address: '237 New Avenue Park, New York',
    amount: 27,
    notes: 'Leak under kitchen sink',
    isReviewed: false,
  },
  {
    _id: 'bk-2',
    serviceTitle: 'Home Cleaning',
    providerName: 'Gorge Cleaning',
    status: 'completed',
    scheduledAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    address: '64 Kind Circle, New York',
    amount: 31,
    notes: 'Deep clean for living room',
    isReviewed: false,
  },
  {
    _id: 'bk-3',
    serviceTitle: 'Laundry Services',
    providerName: 'Jenny Cooper',
    status: 'cancelled',
    scheduledAt: new Date(Date.now() - 3600 * 1000 * 72).toISOString(),
    address: '44 Main Street, New York',
    amount: 21,
    notes: '',
    isReviewed: false,
  },
];

export const CHAT_THREADS = [
  { id: 'th-1', name: 'Jenny Wilson', lastMessage: 'I have reached your house', time: '10:14 AM' },
  { id: 'th-2', name: 'Alfonso Schueler', lastMessage: 'Can we move to 4 PM?', time: '09:20 AM' },
  { id: 'th-3', name: 'Benny Jacobsen', lastMessage: 'Order accepted', time: 'Yesterday' },
  { id: 'th-4', name: 'Kyle Denesik', lastMessage: 'Technician assigned', time: 'Yesterday' },
];

export const CHAT_MESSAGES = {
  'th-1': [
    { from: 'other', text: 'Hi, I am near your home now.', time: '10:01 AM' },
    { from: 'me', text: 'Please call once you arrive.', time: '10:05 AM' },
  ],
};
